# Generated by Django 5.2.17 on 2026-09-05 14:07

import correspondence.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('documents', '0001_initial'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='imap', max_length=8)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('folder', models.CharField(default='INBOX', max_length=255)),
                ('config_fingerprint', models.CharField(blank=True, max_length=64)),
                ('enabled', models.BooleanField(default=False)),
                ('state', models.CharField(default='disabled', max_length=30)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('uidvalidity', models.PositiveBigIntegerField(null=True)),
                ('boundary_uid', models.PositiveBigIntegerField(null=True)),
                ('discovered_uid', models.PositiveBigIntegerField(null=True)),
                ('pending_uidvalidity', models.PositiveBigIntegerField(null=True)),
                ('last_success', models.DateTimeField(null=True)),
                ('last_attempt', models.DateTimeField(null=True)),
                ('last_requested', models.DateTimeField(null=True)),
                ('queued_until', models.DateTimeField(null=True)),
                ('next_attempt_at', models.DateTimeField(null=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_expires', models.DateTimeField(null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('rebuild_requested', models.BooleanField(default=False)),
                ('rebuilding', models.BooleanField(default=False)),
                ('recovery_history', models.JSONField(default=list)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('enabled', True), ('kind', 'imap')), fields=('kind',), name='one_enabled_imap_mailbox')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=255)),
                ('uidvalidity', models.PositiveBigIntegerField()),
                ('uid', models.PositiveBigIntegerField()),
                ('fetch_state', models.CharField(default='pending', max_length=16)),
                ('fetch_error', models.CharField(blank=True, max_length=500)),
                ('fetch_attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('raw_size', models.PositiveBigIntegerField(default=0)),
                ('raw_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('raw_file', models.FileField(blank=True, max_length=200, upload_to=correspondence.models.mail_key)),
                ('subject', models.TextField(blank=True)),
                ('sender_name', models.TextField(blank=True)),
                ('sender_address', models.CharField(blank=True, db_index=True, max_length=320)),
                ('message_id', models.TextField(blank=True)),
                ('in_reply_to', models.TextField(blank=True)),
                ('references', models.JSONField(default=list)),
                ('headers', models.JSONField(default=list)),
                ('body_text', models.TextField(blank=True)),
                ('warnings', models.JSONField(default=list)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('declared_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('todo', 'Do obsłużenia'), ('in_progress', 'W trakcie'), ('waiting', 'Oczekujemy'), ('done', 'Obsłużona'), ('no_action', 'Nie wymaga działania')], db_index=True, default='todo', max_length=16)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=10000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('recovery_candidates', models.JSONField(default=list)),
                ('recovery_status', models.CharField(default='none', max_length=20)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correspondence', to='clients.client')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mail_completed', to=settings.AUTH_USER_MODEL)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='correspondence.mailbox')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mail_work', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correspondence', to='policies.policy')),
            ],
            options={
                'ordering': ['received_at', 'imported_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_key', models.CharField(max_length=100)),
                ('original_name', models.TextField()),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('file', models.FileField(blank=True, max_length=200, upload_to=correspondence.models.mail_key)),
                ('blocked_reason', models.CharField(blank=True, max_length=500)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mail_source', to='documents.document')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='correspondence.message')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='correspondence.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('mailbox', 'folder', 'uidvalidity', 'uid'), name='unique_mail_remote_identity'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('message', 'part_key'), name='unique_mail_mime_part'),
        ),
        migrations.AddConstraint(
            model_name='readreceipt',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_mail_personal_read'),
        ),
    ]
