# Generated by Django 5.2.17 on 2026-09-05 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.UUIDField(db_index=True)),
                ('storage_key', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('source_message_id', models.PositiveBigIntegerField(null=True)),
                ('source_mailbox_id', models.PositiveBigIntegerField(null=True)),
            ],
        ),
    ]
