# Generated by Django 5.2.17 on 2026-09-05 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'W kolejce'), ('running', 'Odczytywanie'), ('succeeded', 'Odczyt zakończony'), ('failed', 'Błąd odczytu')], default='queued', max_length=12)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('attempt_token', models.UUIDField(editable=False, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='documents.document')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EngineResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=100, null=True)),
                ('fields', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('pages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='extraction.extractionjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField(default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('approved_version', models.PositiveIntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='draft', to='documents.document')),
                ('engine_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extraction.engineresult')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('draft_version', models.PositiveIntegerField()),
                ('fields', models.JSONField(default=list)),
                ('profile', models.CharField(max_length=100)),
                ('document_name', models.CharField(max_length=255)),
                ('document_checksum', models.CharField(max_length=64)),
                ('warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='documents.document')),
                ('engine_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extraction.engineresult')),
            ],
            options={
                'ordering': ['-number'],
                'constraints': [models.UniqueConstraint(fields=('document', 'number'), name='unique_document_revision'), models.UniqueConstraint(fields=('document', 'draft_version'), name='unique_approved_draft_version')],
            },
        ),
        migrations.AddIndex(
            model_name='extractionjob',
            index=models.Index(fields=['status', 'lease_until'], name='extraction__status_60217f_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractionjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('document',), name='one_active_extraction_per_document'),
        ),
    ]
