# Generated by Django 5.2.17 on 2026-09-05 13:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


def migrate_drafts(apps, schema_editor):
    Draft = apps.get_model("extraction", "ReviewDraft")
    for draft in Draft.objects.select_related("engine_result").iterator():
        groups, counters = {}, {}
        for field in draft.fields:
            identity = (field["group"], field["index"])
            field.setdefault("group_id", groups.setdefault(identity, str(uuid.uuid4())))
            counters[field["group"]] = max(counters.get(field["group"], 0), field["index"] + 1)
        draft.group_counters = counters
        if draft.engine_result and draft.engine_result.profile:
            draft.profile = draft.engine_result.profile
        draft.save(update_fields=["fields", "group_counters", "profile"])


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedrevision',
            name='origin',
            field=models.CharField(default='engine', max_length=12),
        ),
        migrations.AddField(
            model_name='approvedrevision',
            name='warning_confirmation',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='reviewdraft',
            name='group_counters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='reviewdraft',
            name='origin',
            field=models.CharField(default='engine', max_length=12),
        ),
        migrations.AddField(
            model_name='reviewdraft',
            name='profile',
            field=models.CharField(default='broker_motor_application_v0', max_length=100),
        ),
        migrations.AlterField(
            model_name='approvedrevision',
            name='engine_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='extraction.engineresult'),
        ),
        migrations.AlterField(
            model_name='reviewdraft',
            name='engine_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='extraction.engineresult'),
        ),
        migrations.RunPython(migrate_drafts, migrations.RunPython.noop),
    ]
