# Generated by Django 5.2.17 on 2026-09-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("person", "Osoba"), ("organization", "Organizacja")], max_length=12
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("organization_name", models.CharField(blank=True, max_length=200)),
                ("display_name", models.CharField(editable=False, max_length=220)),
                ("pesel", models.CharField(blank=True, max_length=11)),
                ("nip", models.CharField(blank=True, max_length=20)),
                ("identity_key", models.CharField(blank=True, editable=False, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True, max_length=1000)),
                ("note", models.TextField(blank=True, max_length=10000)),
                ("archived", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("search_text", models.TextField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("identity_key", ""), _negated=True),
                        fields=("identity_key",),
                        name="unique_nonempty_client_identity",
                    )
                ],
            },
        ),
    ]
