# Generated by Django 5.2.17 on 2026-09-05 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("insurer", models.CharField(max_length=200)),
                ("number", models.CharField(max_length=100)),
                ("insurance_type", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("premium", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("currency", models.CharField(default="PLN", max_length=3)),
                ("subject", models.TextField(blank=True, max_length=5000)),
                ("archived", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("search_text", models.TextField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["end_date", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="policy_dates_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("premium__gte", 0), ("premium__isnull", True), _connector="OR"),
                        name="policy_premium_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PolicyParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("policyholder", "Ubezpieczający"), ("insured", "Ubezpieczony")],
                        max_length=20,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policy_roles",
                        to="clients.client",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy", "client", "role"), name="unique_policy_participant_role"
                    )
                ],
            },
        ),
    ]
